export const escapeHTML=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const money=n=>n===null?'Por confirmar':new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN',maximumFractionDigits:0}).format(n);
export const date=s=>new Intl.DateTimeFormat('es-MX',{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'}).format(new Date(s+'T12:00:00Z'));
export const range=t=>date(t.start)+' – '+date(t.end);
export const month=s=>new Intl.DateTimeFormat('es-MX',{month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(s+'-01T12:00:00Z'));
export function filterTrips(trips,f={}){return trips.filter(t=>(!f.destination||t.destination===f.destination)&&(!f.month||t.start.slice(0,7)===f.month)&&(!f.type||t.transport===f.type)&&(!f.budget||(t.price!==null&&t.price<=Number(f.budget)))).sort((a,b)=>f.sort==='price'?(a.price??Infinity)-(b.price??Infinity)||a.start.localeCompare(b.start):a.start.localeCompare(b.start)||a.price-b.price);}
export const priceTerms=t=>[t.priceBasis||'Base de cobro por confirmar',t.occupancy||'Ocupación por confirmar',t.taxes||'Impuestos por confirmar'].join(' · ');
export function quoteText(t,d,details={}){return ['Hola, CieloAzul. Me gustaría solicitar una cotización.',t?`Paquete: ${escapeHTML(t.hotel)} — ${escapeHTML(d.name)}\nReferencia: ${t.id}\nFechas: ${range(t)}\nDuración: ${t.nights+1} días / ${t.nights} noches\nTransporte: ${t.transport==='air'?'Avión':'Autobús'} desde ${escapeHTML(t.origin)}\nPrecio publicado de referencia: ${money(t.price)} MXN (${priceTerms(t)})`:'Viaje a medida.',details.name&&`Nombre: ${details.name}`,details.email&&`Correo: ${details.email}`,details.adults&&`Adultos: ${details.adults}`,details.children&&`Menores: ${details.children}`,details.ages&&`Edades de los menores: ${details.ages}`,details.departure&&`Salida preferida: ${details.departure}`,details.message&&`Comentarios: ${details.message}`,'Por favor, confirmen disponibilidad, precio total, ocupación, impuestos, itinerario y condiciones.'].filter(Boolean).join('\n\n');}
export function card(t,d,selected=false){return `<article class="trip-card" data-id="${t.id}"><a class="photo-link" href="/viajes/${t.id}/" tabindex="-1" aria-hidden="true"><img src="/assets/${t.photo||d.image+'.jpg'}" alt="" width="525" height="700" loading="lazy"><span class="photo-label">${t.transport==='air'?'Avión + hotel':'Autobús + hotel'}</span></a><div class="card-content"><p class="eyebrow">${escapeHTML(d.name)}</p><h3><a href="/viajes/${t.id}/">${escapeHTML(t.hotel)}</a></h3><p class="trip-date">${range(t)}</p><p class="muted">${t.nights+1} días · ${t.nights} noches · ${escapeHTML(t.type)}</p><p class="departure">Desde ${escapeHTML(t.origin)} · ${t.transport==='air'?'Avión':'Autobús'}</p><div class="card-price"><span>Precio publicado de referencia</span><strong>${money(t.price)} <small>MXN</small></strong><span>${escapeHTML(priceTerms(t))}</span></div><details class="card-includes"><summary>Qué incluye</summary><ul>${t.includes.map(escapeHTML).map(i=>`<li>${i}</li>`).join('')}</ul></details><div class="card-actions"><a class="button secondary" href="/viajes/${t.id}/">Ver detalles</a><a class="button" href="/contacto/?viaje=${t.id}">Cotizar este viaje</a></div><label class="compare-label"><input type="checkbox" data-compare="${t.id}" ${selected?'checked':''}> Comparar<span class="sr-only"> ${escapeHTML(t.hotel)}, ${range(t)}</span></label></div></article>`;}
